app:
    name:
    env:
    version:

http_server:
    host:
    port:
    shutdown_timeout:
    idle_timeout:
    read_timeout:
    write_timeout:
    tls:
        enable:
        cert_file:
        key_file:

graphql_server:
    host:
    port:

grpc_server:
    host:
    port:

postgres:
    host:
    port:
    database:
    user:
    password:
    ssl_mode:
    max_conns:
    min_conns:
    max_conn_idle_time:
    max_conn_life_time:
    timeout:

elasticsearch:
    host:
    port:

redis:
    host:
    port:
    password:
    db:
    pool_size:
    min_idle_conns:
    dial_timeout:
    read_timeout:
    write_timeout:

kafka:
    security:
        security_protocol:
        sasl_mechanism:
        sasl_username:
        sasl_password:
    producer:
        client_id:
        bootstrap_servers:
        acks:
        retries:
        retry_backoff_ms:
        linger_ms:
        batch_size:
        compression_type:
        delivery_timeout_ms:
        socket_keep_alive_enable:
    consumer:
        bootstrap_servers:
        group_id:
        auto_offset_reset:
        enable_auto_commit_ms:
        session_timeout_ms:
        max_poll_intervals_ms:
        heart_beat_intervals_ms:
        fetch_min_bytes:
        fetch_wait_max_ms:
        partition_assignment_strategy:
        socket_keep_alive_enable:

zap:
    level:
    development:
    disable_caller:
    disable_stacktrace:
    encoding:
    output_path:
    error_output_path:

jwt:
    secret:
    access_token_ttl:
    refresh_token_ttl:
